# Generated by Django 5.0 on 2026-06-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='block_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
