# Generated by Django 5.0 on 2026-06-25 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_department_block_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.department'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to_hod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hod_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('ONGOING', 'Ongoing'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('SUBMITTED_HOD', 'Submitted to HOD'), ('HOD_APPROVED', 'HOD Approved'), ('SUBMITTED_DEAN', 'Submitted to Dean'), ('DEAN_APPROVED', 'Dean Approved'), ('REJECTED_HOD', 'Rejected by HOD'), ('REJECTED_DEAN', 'Rejected by Dean')], default='ONGOING', max_length=20),
        ),
    ]
