# Generated by Django 5.0 on 2026-06-25 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_task_department_task_is_special_task_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_subtasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='status',
            field=models.CharField(choices=[('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted to HOD'), ('APPROVED_HOD', 'Approved by HOD'), ('REJECTED_HOD', 'Rejected by HOD'), ('COMPLETED', 'Completed')], default='ASSIGNED', max_length=20),
        ),
    ]
