# Generated by Django 5.0 on 2026-06-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_task_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
